// generated by stringer -type=macro_definitions; DO NOT EDIT

package openflow

import "fmt"

const _macro_definitions_name = "OFP_FLOW_PERMANENTOFP_ETH_ALENOFP_MAX_PORT_NAME_LENOFP_MAX_TABLE_NAME_LENOFPFW_ICMP_TYPEOFP_DEFAULT_MISS_SEND_LENDESC_STR_LENOFP_DL_TYPE_NOT_ETH_TYPEOFP_DL_TYPE_ETH2_CUTOFFOFP_TCP_PORTOFP_DEFAULT_PRIORITYOFP_VLAN_NONEOFPQ_ALL"

var _macro_definitions_map = map[macro_definitions]string{
	0:          _macro_definitions_name[0:18],
	6:          _macro_definitions_name[18:30],
	16:         _macro_definitions_name[30:51],
	32:         _macro_definitions_name[51:73],
	64:         _macro_definitions_name[73:88],
	128:        _macro_definitions_name[88:113],
	256:        _macro_definitions_name[113:125],
	1535:       _macro_definitions_name[125:149],
	1536:       _macro_definitions_name[149:172],
	6653:       _macro_definitions_name[172:184],
	32768:      _macro_definitions_name[184:204],
	65535:      _macro_definitions_name[204:217],
	4294967295: _macro_definitions_name[217:225],
}

func (i macro_definitions) String() string {
	if str, ok := _macro_definitions_map[i]; ok {
		return str
	}
	return fmt.Sprintf("macro_definitions(%d)", i)
}
