// generated by stringer -type=of_bsn_pdu_slot_num; DO NOT EDIT

package openflow

import "fmt"

const _of_bsn_pdu_slot_num_name = "BSN_PDU_SLOT_NUM_ANY"

var _of_bsn_pdu_slot_num_index = [...]uint8{0, 20}

func (i of_bsn_pdu_slot_num) String() string {
	i -= 255
	if i >= of_bsn_pdu_slot_num(len(_of_bsn_pdu_slot_num_index)-1) {
		return fmt.Sprintf("of_bsn_pdu_slot_num(%d)", i+255)
	}
	return _of_bsn_pdu_slot_num_name[_of_bsn_pdu_slot_num_index[i]:_of_bsn_pdu_slot_num_index[i+1]]
}
