// generated by stringer -type=ofp_capabilities; DO NOT EDIT

package openflow

import "fmt"

const (
	_ofp_capabilities_name_0 = "OFPC_FLOW_STATSOFPC_TABLE_STATS"
	_ofp_capabilities_name_1 = "OFPC_PORT_STATS"
	_ofp_capabilities_name_2 = "OFPC_STP"
	_ofp_capabilities_name_3 = "OFPC_RESERVED"
	_ofp_capabilities_name_4 = "OFPC_IP_REASM"
	_ofp_capabilities_name_5 = "OFPC_QUEUE_STATS"
	_ofp_capabilities_name_6 = "OFPC_ARP_MATCH_IP"
)

var (
	_ofp_capabilities_index_0 = [...]uint8{0, 15, 31}
	_ofp_capabilities_index_1 = [...]uint8{0, 15}
	_ofp_capabilities_index_2 = [...]uint8{0, 8}
	_ofp_capabilities_index_3 = [...]uint8{0, 13}
	_ofp_capabilities_index_4 = [...]uint8{0, 13}
	_ofp_capabilities_index_5 = [...]uint8{0, 16}
	_ofp_capabilities_index_6 = [...]uint8{0, 17}
)

func (i ofp_capabilities) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ofp_capabilities_name_0[_ofp_capabilities_index_0[i]:_ofp_capabilities_index_0[i+1]]
	case i == 4:
		return _ofp_capabilities_name_1
	case i == 8:
		return _ofp_capabilities_name_2
	case i == 16:
		return _ofp_capabilities_name_3
	case i == 32:
		return _ofp_capabilities_name_4
	case i == 64:
		return _ofp_capabilities_name_5
	case i == 128:
		return _ofp_capabilities_name_6
	default:
		return fmt.Sprintf("ofp_capabilities(%d)", i)
	}
}
