// generated by stringer -type=ofp_port; DO NOT EDIT

package openflow

import "fmt"

const (
	_ofp_port_name_0 = "OFPP_MAX"
	_ofp_port_name_1 = "OFPP_IN_PORTOFPP_TABLEOFPP_NORMALOFPP_FLOODOFPP_ALLOFPP_CONTROLLEROFPP_LOCALOFPP_NONE"
)

var (
	_ofp_port_index_0 = [...]uint8{0, 8}
	_ofp_port_index_1 = [...]uint8{0, 12, 22, 33, 43, 51, 66, 76, 85}
)

func (i ofp_port) String() string {
	switch {
	case i == 65280:
		return _ofp_port_name_0
	case 65528 <= i && i <= 65535:
		i -= 65528
		return _ofp_port_name_1[_ofp_port_index_1[i]:_ofp_port_index_1[i+1]]
	default:
		return fmt.Sprintf("ofp_port(%d)", i)
	}
}
