// generated by stringer -type=ofp_port_features; DO NOT EDIT

package openflow

import "fmt"

const _ofp_port_features_name = "OFPPF_10MB_HDOFPPF_10MB_FDOFPPF_100MB_HDOFPPF_100MB_FDOFPPF_1GB_HDOFPPF_1GB_FDOFPPF_10GB_FDOFPPF_COPPEROFPPF_FIBEROFPPF_AUTONEGOFPPF_PAUSEOFPPF_PAUSE_ASYM"

var _ofp_port_features_map = map[ofp_port_features]string{
	1:    _ofp_port_features_name[0:13],
	2:    _ofp_port_features_name[13:26],
	4:    _ofp_port_features_name[26:40],
	8:    _ofp_port_features_name[40:54],
	16:   _ofp_port_features_name[54:66],
	32:   _ofp_port_features_name[66:78],
	64:   _ofp_port_features_name[78:91],
	128:  _ofp_port_features_name[91:103],
	256:  _ofp_port_features_name[103:114],
	512:  _ofp_port_features_name[114:127],
	1024: _ofp_port_features_name[127:138],
	2048: _ofp_port_features_name[138:154],
}

func (i ofp_port_features) String() string {
	if str, ok := _ofp_port_features_map[i]; ok {
		return str
	}
	return fmt.Sprintf("ofp_port_features(%d)", i)
}
