// generated by stringer -type=ofp_bsn_vport_l2gre_flags; DO NOT EDIT

package openflow

import "fmt"

const (
	_ofp_bsn_vport_l2gre_flags_name_0 = "OF_BSN_VPORT_L2GRE_LOCAL_MAC_IS_VALIDOF_BSN_VPORT_L2GRE_DSCP_ASSIGN"
	_ofp_bsn_vport_l2gre_flags_name_1 = "OF_BSN_VPORT_L2GRE_DSCP_COPY"
	_ofp_bsn_vport_l2gre_flags_name_2 = "OF_BSN_VPORT_L2GRE_LOOPBACK_IS_VALID"
	_ofp_bsn_vport_l2gre_flags_name_3 = "OF_BSN_VPORT_L2GRE_RATE_LIMIT_IS_VALID"
)

var (
	_ofp_bsn_vport_l2gre_flags_index_0 = [...]uint8{0, 37, 67}
	_ofp_bsn_vport_l2gre_flags_index_1 = [...]uint8{0, 28}
	_ofp_bsn_vport_l2gre_flags_index_2 = [...]uint8{0, 36}
	_ofp_bsn_vport_l2gre_flags_index_3 = [...]uint8{0, 38}
)

func (i ofp_bsn_vport_l2gre_flags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ofp_bsn_vport_l2gre_flags_name_0[_ofp_bsn_vport_l2gre_flags_index_0[i]:_ofp_bsn_vport_l2gre_flags_index_0[i+1]]
	case i == 4:
		return _ofp_bsn_vport_l2gre_flags_name_1
	case i == 8:
		return _ofp_bsn_vport_l2gre_flags_name_2
	case i == 16:
		return _ofp_bsn_vport_l2gre_flags_name_3
	default:
		return fmt.Sprintf("ofp_bsn_vport_l2gre_flags(%d)", i)
	}
}
