// generated by stringer -type=ofp_error_type; DO NOT EDIT

package openflow

import "fmt"

const _ofp_error_type_name = "OFPET_HELLO_FAILEDOFPET_BAD_REQUESTOFPET_BAD_ACTIONOFPET_FLOW_MOD_FAILEDOFPET_PORT_MOD_FAILEDOFPET_QUEUE_OP_FAILED"

var _ofp_error_type_index = [...]uint8{0, 18, 35, 51, 72, 93, 114}

func (i ofp_error_type) String() string {
	if i >= ofp_error_type(len(_ofp_error_type_index)-1) {
		return fmt.Sprintf("ofp_error_type(%d)", i)
	}
	return _ofp_error_type_name[_ofp_error_type_index[i]:_ofp_error_type_index[i+1]]
}
