// generated by stringer -type=ofp_flow_mod_failed_code; DO NOT EDIT

package openflow

import "fmt"

const _ofp_flow_mod_failed_code_name = "OFPFMFC_ALL_TABLES_FULLOFPFMFC_OVERLAPOFPFMFC_EPERMOFPFMFC_BAD_EMERG_TIMEOUTOFPFMFC_BAD_COMMANDOFPFMFC_UNSUPPORTED"

var _ofp_flow_mod_failed_code_index = [...]uint8{0, 23, 38, 51, 76, 95, 114}

func (i ofp_flow_mod_failed_code) String() string {
	if i >= ofp_flow_mod_failed_code(len(_ofp_flow_mod_failed_code_index)-1) {
		return fmt.Sprintf("ofp_flow_mod_failed_code(%d)", i)
	}
	return _ofp_flow_mod_failed_code_name[_ofp_flow_mod_failed_code_index[i]:_ofp_flow_mod_failed_code_index[i+1]]
}
