// generated by stringer -type=ofp_port_mod_failed_code; DO NOT EDIT

package openflow

import "fmt"

const _ofp_port_mod_failed_code_name = "OFPPMFC_BAD_PORTOFPPMFC_BAD_HW_ADDR"

var _ofp_port_mod_failed_code_index = [...]uint8{0, 16, 35}

func (i ofp_port_mod_failed_code) String() string {
	if i >= ofp_port_mod_failed_code(len(_ofp_port_mod_failed_code_index)-1) {
		return fmt.Sprintf("ofp_port_mod_failed_code(%d)", i)
	}
	return _ofp_port_mod_failed_code_name[_ofp_port_mod_failed_code_index[i]:_ofp_port_mod_failed_code_index[i+1]]
}
