// generated by stringer -type=ofp_bsn_vport_q_in_q_untagged; DO NOT EDIT

package openflow

import "fmt"

const _ofp_bsn_vport_q_in_q_untagged_name = "OF_BSN_VPORT_Q_IN_Q_UNTAGGED"

var _ofp_bsn_vport_q_in_q_untagged_index = [...]uint8{0, 28}

func (i ofp_bsn_vport_q_in_q_untagged) String() string {
	i -= 65535
	if i >= ofp_bsn_vport_q_in_q_untagged(len(_ofp_bsn_vport_q_in_q_untagged_index)-1) {
		return fmt.Sprintf("ofp_bsn_vport_q_in_q_untagged(%d)", i+65535)
	}
	return _ofp_bsn_vport_q_in_q_untagged_name[_ofp_bsn_vport_q_in_q_untagged_index[i]:_ofp_bsn_vport_q_in_q_untagged_index[i+1]]
}
