// generated by stringer -type=ofp_flow_wildcards; DO NOT EDIT

package openflow

import "fmt"

const _ofp_flow_wildcards_name = "OFPFW_IN_PORTOFPFW_DL_VLANOFPFW_DL_SRCOFPFW_NW_DST_BITSOFPFW_NW_SRC_SHIFTOFPFW_NW_DST_SHIFTOFPFW_DL_TYPEOFPFW_NW_PROTOOFPFW_TP_SRCOFPFW_TP_DSTOFPFW_NW_SRC_ALLOFPFW_NW_SRC_MASKOFPFW_NW_DST_ALLOFPFW_NW_DST_MASKOFPFW_DL_VLAN_PCPOFPFW_NW_TOSOFPFW_ALL"

var _ofp_flow_wildcards_map = map[ofp_flow_wildcards]string{
	1:       _ofp_flow_wildcards_name[0:13],
	2:       _ofp_flow_wildcards_name[13:26],
	4:       _ofp_flow_wildcards_name[26:38],
	6:       _ofp_flow_wildcards_name[38:55],
	8:       _ofp_flow_wildcards_name[55:73],
	14:      _ofp_flow_wildcards_name[73:91],
	16:      _ofp_flow_wildcards_name[91:104],
	32:      _ofp_flow_wildcards_name[104:118],
	64:      _ofp_flow_wildcards_name[118:130],
	128:     _ofp_flow_wildcards_name[130:142],
	8192:    _ofp_flow_wildcards_name[142:158],
	16128:   _ofp_flow_wildcards_name[158:175],
	524288:  _ofp_flow_wildcards_name[175:191],
	1032192: _ofp_flow_wildcards_name[191:208],
	1048576: _ofp_flow_wildcards_name[208:225],
	2097152: _ofp_flow_wildcards_name[225:237],
	4194303: _ofp_flow_wildcards_name[237:246],
}

func (i ofp_flow_wildcards) String() string {
	if str, ok := _ofp_flow_wildcards_map[i]; ok {
		return str
	}
	return fmt.Sprintf("ofp_flow_wildcards(%d)", i)
}
