// generated by stringer -type=ofp_type; DO NOT EDIT

package openflow

import "fmt"

const _ofp_type_name = "OFPT_HELLOOFPT_ERROROFPT_ECHO_REQUESTOFPT_ECHO_REPLYOFPT_EXPERIMENTEROFPT_FEATURES_REQUESTOFPT_FEATURES_REPLYOFPT_GET_CONFIG_REQUESTOFPT_GET_CONFIG_REPLYOFPT_SET_CONFIGOFPT_PACKET_INOFPT_FLOW_REMOVEDOFPT_PORT_STATUSOFPT_PACKET_OUTOFPT_FLOW_MODOFPT_PORT_MODOFPT_STATS_REQUESTOFPT_STATS_REPLYOFPT_BARRIER_REQUESTOFPT_BARRIER_REPLYOFPT_QUEUE_GET_CONFIG_REQUESTOFPT_QUEUE_GET_CONFIG_REPLY"

var _ofp_type_index = [...]uint16{0, 10, 20, 37, 52, 69, 90, 109, 132, 153, 168, 182, 199, 215, 230, 243, 256, 274, 290, 310, 328, 357, 384}

func (i ofp_type) String() string {
	if i >= ofp_type(len(_ofp_type_index)-1) {
		return fmt.Sprintf("ofp_type(%d)", i)
	}
	return _ofp_type_name[_ofp_type_index[i]:_ofp_type_index[i+1]]
}
