// generated by stringer -type=ofp_flow_removed_reason; DO NOT EDIT

package openflow

import "fmt"

const _ofp_flow_removed_reason_name = "OFPRR_IDLE_TIMEOUTOFPRR_HARD_TIMEOUTOFPRR_DELETE"

var _ofp_flow_removed_reason_index = [...]uint8{0, 18, 36, 48}

func (i ofp_flow_removed_reason) String() string {
	if i >= ofp_flow_removed_reason(len(_ofp_flow_removed_reason_index)-1) {
		return fmt.Sprintf("ofp_flow_removed_reason(%d)", i)
	}
	return _ofp_flow_removed_reason_name[_ofp_flow_removed_reason_index[i]:_ofp_flow_removed_reason_index[i+1]]
}
