// generated by stringer -type=ofp_port_config; DO NOT EDIT

package openflow

import "fmt"

const (
	_ofp_port_config_name_0 = "OFPPC_PORT_DOWNOFPPC_NO_STP"
	_ofp_port_config_name_1 = "OFPPC_NO_RECV"
	_ofp_port_config_name_2 = "OFPPC_NO_RECV_STP"
	_ofp_port_config_name_3 = "OFPPC_NO_FLOOD"
	_ofp_port_config_name_4 = "OFPPC_NO_FWD"
	_ofp_port_config_name_5 = "OFPPC_NO_PACKET_IN"
	_ofp_port_config_name_6 = "OFPPC_BSN_MIRROR_DEST"
)

var (
	_ofp_port_config_index_0 = [...]uint8{0, 15, 27}
	_ofp_port_config_index_1 = [...]uint8{0, 13}
	_ofp_port_config_index_2 = [...]uint8{0, 17}
	_ofp_port_config_index_3 = [...]uint8{0, 14}
	_ofp_port_config_index_4 = [...]uint8{0, 12}
	_ofp_port_config_index_5 = [...]uint8{0, 18}
	_ofp_port_config_index_6 = [...]uint8{0, 21}
)

func (i ofp_port_config) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ofp_port_config_name_0[_ofp_port_config_index_0[i]:_ofp_port_config_index_0[i+1]]
	case i == 4:
		return _ofp_port_config_name_1
	case i == 8:
		return _ofp_port_config_name_2
	case i == 16:
		return _ofp_port_config_name_3
	case i == 32:
		return _ofp_port_config_name_4
	case i == 64:
		return _ofp_port_config_name_5
	case i == 2147483648:
		return _ofp_port_config_name_6
	default:
		return fmt.Sprintf("ofp_port_config(%d)", i)
	}
}
