// generated by stringer -type=ofp_nicira_controller_role; DO NOT EDIT

package openflow

import "fmt"

const _ofp_nicira_controller_role_name = "NX_ROLE_OTHERNX_ROLE_MASTERNX_ROLE_SLAVE"

var _ofp_nicira_controller_role_index = [...]uint8{0, 13, 27, 40}

func (i ofp_nicira_controller_role) String() string {
	if i >= ofp_nicira_controller_role(len(_ofp_nicira_controller_role_index)-1) {
		return fmt.Sprintf("ofp_nicira_controller_role(%d)", i)
	}
	return _ofp_nicira_controller_role_name[_ofp_nicira_controller_role_index[i]:_ofp_nicira_controller_role_index[i+1]]
}
