// generated by stringer -type=ofp_hello_failed_code; DO NOT EDIT

package openflow

import "fmt"

const _ofp_hello_failed_code_name = "OFPHFC_INCOMPATIBLEOFPHFC_EPERM"

var _ofp_hello_failed_code_index = [...]uint8{0, 19, 31}

func (i ofp_hello_failed_code) String() string {
	if i >= ofp_hello_failed_code(len(_ofp_hello_failed_code_index)-1) {
		return fmt.Sprintf("ofp_hello_failed_code(%d)", i)
	}
	return _ofp_hello_failed_code_name[_ofp_hello_failed_code_index[i]:_ofp_hello_failed_code_index[i+1]]
}
