// generated by stringer -type=ofp_port_reason; DO NOT EDIT

package openflow

import "fmt"

const _ofp_port_reason_name = "OFPPR_ADDOFPPR_DELETEOFPPR_MODIFY"

var _ofp_port_reason_index = [...]uint8{0, 9, 21, 33}

func (i ofp_port_reason) String() string {
	if i >= ofp_port_reason(len(_ofp_port_reason_index)-1) {
		return fmt.Sprintf("ofp_port_reason(%d)", i)
	}
	return _ofp_port_reason_name[_ofp_port_reason_index[i]:_ofp_port_reason_index[i+1]]
}
