// generated by stringer -type=ofp_bad_request_code; DO NOT EDIT

package openflow

import "fmt"

const _ofp_bad_request_code_name = "OFPBRC_BAD_VERSIONOFPBRC_BAD_TYPEOFPBRC_BAD_STATOFPBRC_BAD_EXPERIMENTEROFPBRC_BAD_SUBTYPEOFPBRC_EPERMOFPBRC_BAD_LENOFPBRC_BUFFER_EMPTYOFPBRC_BUFFER_UNKNOWN"

var _ofp_bad_request_code_index = [...]uint8{0, 18, 33, 48, 71, 89, 101, 115, 134, 155}

func (i ofp_bad_request_code) String() string {
	if i >= ofp_bad_request_code(len(_ofp_bad_request_code_index)-1) {
		return fmt.Sprintf("ofp_bad_request_code(%d)", i)
	}
	return _ofp_bad_request_code_name[_ofp_bad_request_code_index[i]:_ofp_bad_request_code_index[i+1]]
}
