// generated by stringer -type=ofp_bad_action_code; DO NOT EDIT

package openflow

import "fmt"

const _ofp_bad_action_code_name = "OFPBAC_BAD_TYPEOFPBAC_BAD_LENOFPBAC_BAD_EXPERIMENTEROFPBAC_BAD_EXPERIMENTER_TYPEOFPBAC_BAD_OUT_PORTOFPBAC_BAD_ARGUMENTOFPBAC_EPERMOFPBAC_TOO_MANYOFPBAC_BAD_QUEUE"

var _ofp_bad_action_code_index = [...]uint8{0, 15, 29, 52, 80, 99, 118, 130, 145, 161}

func (i ofp_bad_action_code) String() string {
	if i >= ofp_bad_action_code(len(_ofp_bad_action_code_index)-1) {
		return fmt.Sprintf("ofp_bad_action_code(%d)", i)
	}
	return _ofp_bad_action_code_name[_ofp_bad_action_code_index[i]:_ofp_bad_action_code_index[i+1]]
}
