// generated by stringer -type=ofp_queue_op_failed_code; DO NOT EDIT

package openflow

import "fmt"

const _ofp_queue_op_failed_code_name = "OFPQOFC_BAD_PORTOFPQOFC_BAD_QUEUEOFPQOFC_EPERM"

var _ofp_queue_op_failed_code_index = [...]uint8{0, 16, 33, 46}

func (i ofp_queue_op_failed_code) String() string {
	if i >= ofp_queue_op_failed_code(len(_ofp_queue_op_failed_code_index)-1) {
		return fmt.Sprintf("ofp_queue_op_failed_code(%d)", i)
	}
	return _ofp_queue_op_failed_code_name[_ofp_queue_op_failed_code_index[i]:_ofp_queue_op_failed_code_index[i+1]]
}
