// generated by stringer -type=ofp_queue_properties; DO NOT EDIT

package openflow

import "fmt"

const _ofp_queue_properties_name = "OFPQT_NONEOFPQT_MIN_RATE"

var _ofp_queue_properties_index = [...]uint8{0, 10, 24}

func (i ofp_queue_properties) String() string {
	if i >= ofp_queue_properties(len(_ofp_queue_properties_index)-1) {
		return fmt.Sprintf("ofp_queue_properties(%d)", i)
	}
	return _ofp_queue_properties_name[_ofp_queue_properties_index[i]:_ofp_queue_properties_index[i+1]]
}
