// generated by stringer -type=ofp_action_type; DO NOT EDIT

package openflow

import "fmt"

const (
	_ofp_action_type_name_0 = "OFPAT_OUTPUTOFPAT_SET_VLAN_VIDOFPAT_SET_VLAN_PCPOFPAT_STRIP_VLANOFPAT_SET_DL_SRCOFPAT_SET_DL_DSTOFPAT_SET_NW_SRCOFPAT_SET_NW_DSTOFPAT_SET_NW_TOSOFPAT_SET_TP_SRCOFPAT_SET_TP_DSTOFPAT_ENQUEUE"
	_ofp_action_type_name_1 = "OFPAT_EXPERIMENTER"
)

var (
	_ofp_action_type_index_0 = [...]uint8{0, 12, 30, 48, 64, 80, 96, 112, 128, 144, 160, 176, 189}
	_ofp_action_type_index_1 = [...]uint8{0, 18}
)

func (i ofp_action_type) String() string {
	switch {
	case 0 <= i && i <= 11:
		return _ofp_action_type_name_0[_ofp_action_type_index_0[i]:_ofp_action_type_index_0[i+1]]
	case i == 65535:
		return _ofp_action_type_name_1
	default:
		return fmt.Sprintf("ofp_action_type(%d)", i)
	}
}
