// generated by stringer -type=ofp_bsn_vport_status; DO NOT EDIT

package openflow

import "fmt"

const _ofp_bsn_vport_status_name = "OF_BSN_VPORT_STATUS_OKOF_BSN_VPORT_STATUS_FAILED"

var _ofp_bsn_vport_status_index = [...]uint8{0, 22, 48}

func (i ofp_bsn_vport_status) String() string {
	if i >= ofp_bsn_vport_status(len(_ofp_bsn_vport_status_index)-1) {
		return fmt.Sprintf("ofp_bsn_vport_status(%d)", i)
	}
	return _ofp_bsn_vport_status_name[_ofp_bsn_vport_status_index[i]:_ofp_bsn_vport_status_index[i+1]]
}
