// generated by stringer -type=ofp_packet_in_reason; DO NOT EDIT

package openflow

import "fmt"

const _ofp_packet_in_reason_name = "OFPR_NO_MATCHOFPR_ACTION"

var _ofp_packet_in_reason_index = [...]uint8{0, 13, 24}

func (i ofp_packet_in_reason) String() string {
	if i >= ofp_packet_in_reason(len(_ofp_packet_in_reason_index)-1) {
		return fmt.Sprintf("ofp_packet_in_reason(%d)", i)
	}
	return _ofp_packet_in_reason_name[_ofp_packet_in_reason_index[i]:_ofp_packet_in_reason_index[i+1]]
}
