// generated by stringer -type=ofp_flow_mod_flags; DO NOT EDIT

package openflow

import "fmt"

const (
	_ofp_flow_mod_flags_name_0 = "OFPFF_SEND_FLOW_REMOFPFF_CHECK_OVERLAP"
	_ofp_flow_mod_flags_name_1 = "OFPFF_EMERG"
)

var (
	_ofp_flow_mod_flags_index_0 = [...]uint8{0, 19, 38}
	_ofp_flow_mod_flags_index_1 = [...]uint8{0, 11}
)

func (i ofp_flow_mod_flags) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ofp_flow_mod_flags_name_0[_ofp_flow_mod_flags_index_0[i]:_ofp_flow_mod_flags_index_0[i+1]]
	case i == 4:
		return _ofp_flow_mod_flags_name_1
	default:
		return fmt.Sprintf("ofp_flow_mod_flags(%d)", i)
	}
}
