// generated by stringer -type=ofp_config_flags; DO NOT EDIT

package openflow

import "fmt"

const _ofp_config_flags_name = "OFPC_FRAG_NORMALOFPC_FRAG_DROPOFPC_FRAG_REASMOFPC_FRAG_MASK"

var _ofp_config_flags_index = [...]uint8{0, 16, 30, 45, 59}

func (i ofp_config_flags) String() string {
	if i >= ofp_config_flags(len(_ofp_config_flags_index)-1) {
		return fmt.Sprintf("ofp_config_flags(%d)", i)
	}
	return _ofp_config_flags_name[_ofp_config_flags_index[i]:_ofp_config_flags_index[i+1]]
}
